spring:
  application:
    name: ms-ordenes
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      fail-fast: true
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.example.msordenes: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO