spring:
  application:
    name: ms-auth
  config:
    import: "optional:configserver:http://localhost:8888"  # Config Server opcional
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      fail-fast: true
  profiles:
    active: dev
  main:
    allow-circular-references: true  # Permite referencias circulares entre beans

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
    com.example.msauth: DEBUG